spring:
  profiles:
    active: student-service

---

spring:
  config:
    activate:
      on-profile: student-service

  datasource:
    url: jdbc:postgresql://postgresdb:5432/studentdb
    username: postgres
    password: 2001
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
