spring:
  profiles:
    active: course-service

---

spring:
  config:
    activate:
      on-profile: course-service

  datasource:
    url: jdbc:postgresql://localhost:5432/coursedb
    username: postgres
    password: 2001
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082
