spring:
  profiles:
    active: registration-service

---

spring:
  config:
    activate:
      on-profile: registration-service

  datasource:
    url: jdbc:postgresql://localhost:5432/registrationdb
    username: postgres
    password: 2001
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

student:
  service:
    url: http://student-service:8081

server:
  port: 8083
